### PR TITLE
Updated Mutations & Queries with authentication (Not Completely Tested)

### PR DESCRIPTION
**Pull request by bhavberi**
@v15hv4 

We need to test everything out asap and then push the branch.

### CODE REVIEW

**Comment by v15hv4** [comment]
I've renamed the queries to remove the 'get' prefix because it's more in line with the graphql conventions, let's keep this consistent across all our services.

Issues to resolve:
- [ ]  `activeClubs` should not require authentications (STR: currently running the query requires you to be signed in)
- [ ] `club` should not require authentication either (STR: same as above) [if the club's status is not active, then check for auth status and role]
- [ ] same as above for `members` (STR: same as above) [if the club's status is not active & user is not cc, return access denied]

**Comment by v15hv4** [comment]
editClub errors out if social > other_links is null. STR below.

query:
```
mutation EditClub($clubInput: EditClubInput!) {
  editClub(clubInput: $clubInput) {
    cid
  }
}
``` 
variables:
```
{
  "clubInput": {
    "cid": "HC",
    "socials": {
      "instagram": "https://www.instagram.com/0x1337iiith/"
    },
    "name": "0x1337",
    "email": "hacking.clubs@students.iiit.ac.in"
  }
}
```

error message:
```
"1 validation error for Social\nother_links\n  'NoneType' object is not iterable (type=type_error)"
```

**Comment by v15hv4** [comment]
editClub errors out if social > other_links is null. STR below.

query:
```
mutation EditClub($clubInput: EditClubInput!) {
  editClub(clubInput: $clubInput) {
    cid
  }
}
``` 
variables:
```
{
  "clubInput": {
    "cid": "HC",
    "socials": {
      "instagram": "https://www.instagram.com/0x1337iiith/"
    },
    "name": "0x1337",
    "email": "hacking.clubs@students.iiit.ac.in"
  }
}
```

error message:
```
"1 validation error for Social\nother_links\n  'NoneType' object is not iterable (type=type_error)"
```

**Comment by bhavberi** [comment]
> editClub errors out if social > other_links is null. STR below.
> 
> query:
> 
> ```
> mutation EditClub($clubInput: EditClubInput!) {
>   editClub(clubInput: $clubInput) {
>     cid
>   }
> }
> ```
> 
> variables:
> 
> ```
> {
>   "clubInput": {
>     "cid": "HC",
>     "socials": {
>       "instagram": "https://www.instagram.com/0x1337iiith/"
>     },
>     "name": "0x1337",
>     "email": "hacking.clubs@students.iiit.ac.in"
>   }
> }
> ```
> 
> error message:
> 
> ```
> "1 validation error for Social\nother_links\n  'NoneType' object is not iterable (type=type_error)"
> ```

@v15hv4 
I think this issue is now resolved. Kindly check and let me know for any changes.

**Comment by v15hv4** [comment]
Assign role on `createClub`. I've added a new mutation to the users service:

query:
```
mutation UpdateRole($roleInput: RoleInput!) {
  updateRole(roleInput: $roleInput)
}
```

variables:
```
{
  "roleInput": {
    "role": "club",
    "uid": "club.name",
  }
}
```

**Pull request merged**
